services:
  app:
    ports:
      - 8080:8080
      # internal, internals의 entrypoint 노출
      - 30080:30080
      - 30443:30443
      # reinternal, reinternals의 entrypoint 노출
      - 32080:32080
      - 32443:32443
    labels:
      # traefik
      - traefik.enable=true
      - traefik.http.routers.$SERVICE.entrypoints=reinternals
      - traefik.http.routers.${SERVICE}.rule=Host(`${DOMAIN_INTERNAL}`)
      - traefik.http.routers.${SERVICE}.service=${SERVICE}
      - traefik.http.services.${SERVICE}.loadbalancer.server.port=${APP_PORT}
    volumes:
      - ./_v/traefik/acme:/acme
      - ./_v/traefik/users:/etc/traefik/users
      - ./_v/traefik/cert:/cert
      - ./_v/traefik/logs:/logs

---
services:
  whoami:
    image: containous/whoami
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.entrypoints=reinternals
      - traefik.http.routers.whoami.rule=PathPrefix(`/`)
      - traefik.http.routers.whoami.priority=1
      - traefik.http.services.whoami.loadbalancer.server.port=80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - WHOAMI_HOSTNAME_AND_IP=true
    restart: unless-stopped