################################################################
#
# Configuration sample for Traefik v2.
#
# master
# For Traefik v2: https://github.com/traefik/traefik/blob/master/traefik.sample.yml
# sample
# For Traefik v1: https://github.com/traefik/traefik/blob/v1.7/traefik.sample.toml
#
################################################################

################################################################
# Global configuration
################################################################

global:
  checkNewVersion: true
  sendAnonymousUsage: true

################################################################
# Traefik logs configuration
################################################################

log:
  level: DEBUG

################################################################
# Access logs configuration
################################################################

accessLog:
  filePath: /traefik.log
  bufferingSize: 100
  filters:
    statusCodes: ["400-499"]

################################################################
# API and dashboard configuration
################################################################

api:
  insecure: true

################################################################
# EntryPoints configuration
################################################################

entryPoints:
  web:
    address: :80
    # Redirect
    http:
      redirections:
        entryPoint:
          to: webs
          scheme: https
          permanent: true
  webs:
    address: :443
    http:
      tls:
        certResolver: leresolver

  # internal
  # 리다이렉트가능한 entrypoint
  reinternal:
    address: :32080
    # Redirect
    http:
      redirections:
        entryPoint:
          # 여기서 webs로 리다이렉트하는 이유는 gateway에서 80, 443 포트를 받아서 내부에서 호스트명으로 어떤 클러스터를 사용할것인지 설정하기 때문이다.
          # 그래서 http로 와도 https로 리다이렉트하고 https는 gateway에서 reinternals 포트로 트래픽을 전달해준다.
          to: webs
          scheme: https
          permanent: true
  reinternals:
    address: :32443
    http:
      tls:
        options: default
  # 리다이렉트 없는 entrypoint
  internal:
    address: :30080
  internals:
    address: :30443
    http:
      tls:
        options: default

################################################################
# Docker configuration backend
################################################################

providers:
  docker:
    watch: true
    endpoint: unix:///var/run/docker.sock
    # docker.sock을 확인하다보니까 모든 container가 traefik dashboard에서 확인이 가능하다.
    # traefik.enabled 라벨이없으면 traefik dashboard에 노출되지 않도록하는 옵션
    exposedByDefault: false
    network: traefik_proxy
  file:
    directory: /rules
    watch: true

################################################################
# 인증서
# example: https://doc.traefik.io/traefik/https/acme/
################################################################

certificatesResolvers:
  leresolver:
    acme:
      email: certificate@hyeon.pro
      storage: /acme/acme.json
      httpChallenge:
        entryPoint: web
